### ISSUE TITLE
Progress Upload Bar Not Working

### ISSUE THREAD

**Issue by interpegasus** [skoczen/django-ajax-uploader#18]
Hi,

I would like to know if the Ajax Uploader supports a progress bar for Amazon S3?
Currently it goes from 0 to 100% before the upload finishes.

Thanks!

**Comment by skoczen** [comment]
Hello,

I see a progress bar using S3, but only for larger files.  How big is the file you're trying?

**Comment by interpegasus** [comment]
Hi,

I tried different file sizes up to around 150 Mb and it went from 1 to 100 before finishing the upload.
Maybe it is just an issue with my configuration. Thanks!
