### ISSUE TITLE
python 2.5 issue

### ISSUE THREAD

**Issue by ghost** [skoczen/django-ajax-uploader#19]
The module io is not available for python 2.5 and less. so it creates an exception when importing the file local.py.

**Comment by skoczen** [comment]
Hey elavoine,

I'm going to close this wontfix. Python 2.6 is 4+ years old. If folks are still running python 2.5 in production, it's time to upgrade.

Alternatively, if you want to backport and patch it, a pull request would be accepted!

Cheers,
-Steven
