### ISSUE TITLE
S3 Upload

### ISSUE THREAD

**Issue by parsingeye** [skoczen/django-ajax-uploader#20]
Uploaded files are empty (0 bytes)

**Comment by skoczen** [comment]
Since this is working for other folks (and me, in several production sites), I'm going to assume it's something with your setup.

If you'd like to post more details, your config, etc, it'd be possible to help, but without them, I'm closing this issue.

**Comment by parsingeye** [comment]
Everything works fine with LocalUploadBackend. 
For s3 backend in view.py I imported

from ajaxuploader.views import AjaxFileUploader
from ajaxuploader.backends.s3 import S3UploadBackend

and added 
import_uploader = AjaxFileUploader(backend=S3UploadBackend, NUM_PARALLEL_PROCESSES=5)

in settings.py

AWS_ACCESS_KEY_ID = "..."
AWS_SECRET_ACCESS_KEY = "..."
AWS_BUCKET_NAME = "bucket-name"

Everything works fine except files in bucket have zero bytes.
I don't know if there is anything else I can add as config.

**Comment by ghost** [comment]
I'm also having this issue, don't know why but when I switched from botoS3 storage to S3 storage, it starts to work. weird!

**Comment by zallarak** [comment]
How did you switch from botoS3 storage to S3 storage? I use boto and have the same issue.
