### ISSUE TITLE
Failed uploads

### ISSUE THREAD

**Issue by adambratt** [skoczen/django-ajax-uploader#23]
I'm not sure what's going wrong here. I followed the installation instructions but when ever I try to upload a file over about 1MB I get an upload failed message.

Additionally, I can upload files under 1MB with the local backend but when I try and upload to the S3 backend it just creates an empty 0 byte file in the bucket.

**Comment by zallarak** [comment]
"MultiPart Upload is a relatively recent additon to the S3 service that is designed to make it easier to upload large files.  Each part must be 5MB (except the last part, obviously) and is generally only useful on files that are > 100MB."

The S3Backend over here uses this, so it wouldn't work.

**Comment by adambratt** [comment]
Ok. So basically I have to either split mine up into multiple files or rewrite the S3Backend to do it a different way?

**Comment by zallarak** [comment]
@adamjon858, Rewrite S3Backend to do it in a different way. I'm shortly going to attempt the same thing. Let me know if you get something working. It automatically splits it into multiple files for you -- it is meant for uploads > 100MB. I was using small files, <100MB, I don't know of your situation though.

**Comment by zallarak** [comment]
This did the trick. Comment out upload_chunk and subclass upload. It isn't a streaming upload though, that's a project for another day. If you have files with the same name coming in, make sure you're randomizing them to some extent to avoid collisions. 

```
def upload(self, uploaded, filename, raw_data):
    k = Key(self._bucket)
    k.key = filename
    chunk = uploaded.read()
    k.set_contents_from_string(chunk):
    # do a test here to see if it was successful, I generated a url
        return True
    else:
        return False
```

**Comment by adambratt** [comment]
Still not working for me. All files show up in S3 but they are 0 bytes and contain nothing.

**Comment by zallarak** [comment]
Well, if you post your source I can try and help.

**Comment by ghost** [comment]
Hi guys,

After speaking with zallarak and a few debugging sessions I found a solution for that ;)

```
def upload_chunk(self, chunk):
    self._counter += 1
    buffer = StringIO()
    buffer.write(chunk)
    buffer.seek(0)
    self._pool.apply_async(
        self._mp.upload_part_from_file(buffer, self._counter))
    buffer.close()
```

As you can see I added buffer.seek(0) before executing upload_part_from_file that solves the issue.

The explanation for that is simple, after buffer.write(chunk) being executed buffer's handle is being set to the end of the buffer and boto's mp_upload_par_from_file tries to upload the buffer but think he already reached the end of the file.

Hope that helps.

**Comment by zallarak** [comment]
@nopped thanks for posting that!

**Comment by skoczen** [comment]
Doing a catch-up clean-out of issues on ajaxuploader. Looks like this one stalled/resolved, so I'm closing it. Please re-open if that's not right!
