### ISSUE TITLE
I Need a Django sample to customize the backend (upload_filename, AbstractUploadBackend)

### ISSUE THREAD

**Issue by ghost** [skoczen/django-ajax-uploader#30]
I Know Django is providing flexible and powerful feature, but not well documented, as i am a Bit new on Django, could you please provide a sample on how customize myself the Upload feature (Setup, Chunk, filename and complete). thanks

**Comment by skoczen** [comment]
Hey there,

I apologize, but I don't actually have time to provide support for this project.  I'd dig into python and django a bit - the customizing the backend is just a matter of subclassing the backend you want to tweak, then providing it as an argument.  If the previous sentence doesn't make complete sense, I'd dig into python a bit more, and then come back to the uploader.

Also, I welcome any pull requests with better docs if you want to submit them!

Thanks for your understanding!
