### ISSUE TITLE
Update file-uploader.js ?

### ISSUE THREAD

**Issue by owenmead** [skoczen/django-ajax-uploader#36]
Had a bit of back and forth with rnicholus
https://github.com/valums/file-uploader/issues/443

Thinking it would be a good idea to update the file-uploader.js as it's about 7 months old:
https://github.com/valums/file-uploader/

**Comment by skoczen** [comment]
Seems like a good idea to me - will try to pull it in this long (US) weekend.  If you've got time before I do, feel free to send over a pull with the new fileuploader!

**Comment by obiwanus** [comment]
Maybe it would be better if the fileuploader wasn't included here at all? It seems that this library is going to be compatible with the fileuploader for a long time (as the upload logic itself is not going to be changed).

Fineuploader.js is now being actively developed, so any new version will become obsolete soon. Why don't you just delete the old version and list it as a dependency in the readme?

**Comment by skoczen** [comment]
The general recommendation is to use fineuploader, at this point, but I've left the existing one in to not break people's projects.

Doing a catch-up clean-out of issues on ajaxuploader. Looks like this one's resolved, so I'm closing it. Please re-open if that's not right!

Thanks!
