### ISSUE TITLE
InputName is hardcoded as 'qqfile'

### ISSUE THREAD

**Issue by obiwanus** [skoczen/django-ajax-uploader#37]
During an ajax upload filename is getting from GET by the hardcoded key `qqfile`:

``` javascript
try:
    filename = request.GET['qqfile']
except KeyError:
    return HttpResponseBadRequest("AJAX request not valid")
```

Whereas it might be changed in a fileuploader instance (`inputName` option).

**Comment by skoczen** [comment]
That's definitely possible - would you mind putting a PR together with the changes and docs?  

I'm also doing a catch-up clean-out of issues on ajaxuploader. Given that this has been a year, it looks like this one's stalled, so I'm closing it. Please re-open if that's not right!

Thanks!
