### ISSUE TITLE
Add support in js library to mention notAllowedExtensions

### ISSUE THREAD

**Issue by intellisense** [skoczen/django-ajax-uploader#39]
As we have allowedExtensions property in js library, we should also have notAllowedExtensions which will make things little bit easier. For example i want the user to be able to upload all files instead of those files which has extension .exe

If user has defined allowedExtensions always take priority over notAllowedExtensions. For example if mistakenly i have defined a .exe extension in both then allowedExtension should always consider first.

**Comment by skoczen** [comment]
I'm closing this, as it's part of fineuploader, not this library - please reopen if that seems incorrect!
