### ISSUE TITLE
filtering by mimetype

### ISSUE THREAD

**Issue by gregorysemah** [skoczen/django-ajax-uploader#45]
Hi GoodCloud,

Is there any way to prevent uploading (on client side or on server side, in the backend) from specific file extension.
For example I just want to upload png's and epub's
Is there a consistant way to do this? with a little bit of code ?

Thanks for your answer

**Comment by skoczen** [comment]
Hi gregory,

I'd look into fineuploader's documentation on filtering certain file extensions.  You could also override the upload_complete method on the backend, or hook into the signal.

I'm also doing a catch-up clean-out of issues on ajaxuploader. Looks like this one's stalled, so I'm closing it. Please re-open if that's not right!

Thanks,
-Steven
