### ISSUE TITLE
Detecting upload cancellation in backend

### ISSUE THREAD

**Issue by Ali-Said** [skoczen/django-ajax-uploader#48]
My issue is when the uploading is canceled midway, an empty file (image in my case) gets uploaded, I need to deal with that issue on the back-end side of my code so I need to ask how to detect the upload cancellation in the back-end and where is that triggered from in the front end, do I need to write a function onCancel or is it taken care of automatically.

Thanks in advance

**Comment by skoczen** [comment]
Hey there,

I'd check out the newest versions of fineuploader - it'll have better support for this sort of thing.

I'm also doing a catch-up clean-out of issues on ajaxuploader. Looks like this one's stalled, so I'm closing it. Please re-open if that's not right!

Thanks,
-Steven
