### ISSUE TITLE
Expecting AWS_UPLOAD_CLEINT_KEY and AWS_UPLOAD_CLIENT_SECRET_KEY for default backend

### ISSUE THREAD

**Issue by borgesalkan** [skoczen/django-ajax-uploader#50]
The code is not gracefully handling the case when there are no AWS keys present in the settings.py. This is the case I came across while using the default backend. 

Probably the error is in here https://github.com/GoodCloud/django-ajax-uploader/blob/master/ajaxuploader/views/s3.py#L10-L19.

**Comment by skoczen** [comment]
This is fixed, and will go out this afternoon with 0.3.5.  Thanks for the report!

**Comment by borgesalkan** [comment]
Thank you.
