### ISSUE TITLE
Please add loading.gif

### ISSUE THREAD

**Issue by ribalba** [skoczen/django-ajax-uploader#51]
Hello,

in the css [1] in line 27 you specify a loading.gif this is however not in the git repo. Maybe you could add one? Otherwise I am more than welcome to send you a pull request where I have added a little gif.

Cheers Didi

[1] https://github.com/GoodCloud/django-ajax-uploader/blob/master/ajaxuploader/static/ajaxuploader/css/fileuploader.css

**Comment by winonatong** [comment]
I see that loading.gif was added yesterday, and the pypi package was updated to 0.3.2, however, the pypi package is still missing loading.gif.

**Comment by skoczen** [comment]
Forgot to put in the manifest file - should be there now, on 0.3.3!
