### ISSUE TITLE
using fine uploader uploaded file is empty

### ISSUE THREAD

**Issue by kuyucakli** [skoczen/django-ajax-uploader#53]
Hi,
I am using fine uploader.
In backends base.py
line   ---> chunk = uploaded.read(self.BUFFER_SIZE)

chunk is empty

and the file uploaded is empty...

Why?

**Comment by skoczen** [comment]
Hey Burakk, 

I'd need more info to be able to debug and help out on that.  It's definitely working for me and lots of other folks, so if you have details, please post them!

I'm also doing a catch-up clean-out of issues on ajaxuploader. Looks like this one's stalled, so I'm closing it. Please re-open if that's not right!

Thanks,
-Steven
