### ISSUE TITLE
the import.html in example

### ISSUE THREAD

**Issue by liaofeng** [skoczen/django-ajax-uploader#65]
I am confused with the following code:

```
def start(request):
    csrf_token = get_token(request)
    return render_to_response('import.html',
        {'csrf_token': csrf_token}, context_instance = RequestContext(request))
```

I know the meaning of the code,
but dont know when will django-ajax-uploader use request the method `start`, 
and no template named import.html in the repository

**Comment by derek-adair** [comment]
the uri /start/ is what your users will navigate  to to trigger the upload UI / scripts.  This project requires you to create your own template which invokes [fineuploader](https://github.com/FineUploader/fine-uploader) (or the included js script in this repo).    This will look something like...

![screen shot 2014-12-30 at 8 33 37 am](https://cloud.githubusercontent.com/assets/847236/5579869/a022f596-8ffe-11e4-92a3-4f29e272fe91.png)

The JavaScript code will be pointed to /ajax-upload/ or {% url 'my_ajax_upload' %} if you follow the [installation instructions](https://github.com/GoodCloud/django-ajax-uploader#step-1-install-django-ajax-uploader-).

I am actually working on modifying this project to work out-of-the-box with Django Fine Uploader in a way that I would like to use it. [Here is](https://github.com/derek-adair/django-fine-uploader/) what i have so far!  Its not a direct fork, but i will be shoehorning the same capabilities shortly.  Currently its a single backend support (S3).  A short list of things i will be adding is, multiple backends, more signals to make integrating easier (probably just delete), as well as making it simple to include the js widget on any page in your app.

**Comment by skoczen** [comment]
Hey @derek-adair , for what it's worth, you're welcome to make it a fork of this project and send over a PR - it could use the consistent maintenance, and given its installed base and SEO, it'd get more eyeballs on your work.

@liaofeng , I think @derek-adair has answered your question, so closing this issue up - re-open if you've still got questions!
