### ISSUE TITLE
how to prevent auto submit and do an onclick submit of another element

### ISSUE THREAD

**Issue by zubairalam** [skoczen/django-ajax-uploader#67]
As long as a file is selected its being uploaded to server. I want to send this later point of time, say on some other button click. How can i do this.

**Comment by skoczen** [comment]
Hi @zubairalam , 

You'd want to write a custom handler then - the [documentation for fineuploader](http://docs.fineuploader.com/branch/master/api/options.html) (particularly `autoUpload`) are where you'd want to start.

Best of luck!
