### ISSUE TITLE
Practical to switch to Django-Storages?

### ISSUE THREAD

**Issue by derek-adair** [skoczen/django-ajax-uploader#69]
I'm thinking it may be beneficial to switch to using django-storages instead of the custom backends implemented here.  Maybe this is pointless, i'm still not _that_ savvy with django/python so perhaps that doesn't make sense.

**Comment by skoczen** [comment]
So, django-storages would solve a different problem, and it's assumed that you can use storages in your normal django install, and leverage that here, if you want.  Does that make sense, or am I talking crazy?

**Comment by derek-adair** [comment]
From my perspective, this project has four major functions;

1) Parsing form / multipart data
2) Handling file upload / naming conventions
**2a) Including storage**
4) Easy hooks w/ triggers

Leveraging django storages would allow this project to drop its custom backend code.  Which would be a pretty big win as far as i'm concerned.  Currently, for example, the s3 backend does not function.  I believe the amazon s3 api has changed, i couldn't figure it out.  

Django-storages would be a drop-in replacement that comes for free with a huge test suite.  Although, the maintainer dropped off the face of the planet so a [redux repo has appeared](https://pypi.python.org/pypi/django-storages-redux/1.2).

**Comment by skoczen** [comment]
I totally see your point, and that seems actually really sane. 

There may still be a case for custom backends (for instance, the s3 backend, which still works for me, is significantly faster to upload than the default, non-parallelized methods).

But broadly, I can definitely get behind this change.

**Comment by derek-adair** [comment]
OKKKKK SOOOOO.  about 3 years later... and a whole bunch of python knowledge later...

This does indeed work OUT OF THE BOX with django storages.  Simply;

1) install django storages
2) follow instructions for installing the DefaultStorageUploadBackend

Thx for your hard work @skoczen, still working in django 2.0.8
